# Generated by Django 5.1 on 2024-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
