# Generated by Django 5.1 on 2024-08-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_inflow_slug'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflow', to='products.product', verbose_name='produtos'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='quantity',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflow', to='suppliers.supplier', verbose_name='fornecedores'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
