# Generated by Django 5.1.1 on 2024-10-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
